### ISSUE TITLE
Module3- Chapter3 missing data file

### ISSUE THREAD

**Issue by AcWd** [PacktPublishing/Data-Science-With-Python#1]
the data file for Module3 Chapter3 leagues_NBA_2014_games_games.csv is missing 

Cam you please update the file ?

**Comment by jimmy-walker** [comment]
I cannot find too. So I search the csv file from [here](https://github.com/NateCham/NBANLPCommentary)

**Comment by xuzhe0628** [comment]
Maybe you can try [this file](https://github.com/pm429015/NBA_Machine-Learning/blob/master/NBA2012-15/leagues_NBA_2014_games_games.csv).

**Comment by techsachinkumar** [comment]
Added missing csv file.

Closed.
